change the inputs of metrics
gomate-community/rageval pull request #103
Opened 2024-05-20 06:03 UTC by bugtig6351

2024-05-28 01:55 UTC, faneshion requested changes

2024-05-28 01:55 UTC, faneshion commented on rageval/metrics/_answer_accuracy.py
> +        references
I suggest using parameters`pred_answers` and `ref_answers` for clarity, as some metrics may require three or more parameters in addition to `predictions` and `references`.

2024-05-28 01:55 UTC, faneshion commented on rageval/metrics/_answer_bleu.py
> +    def _compute_single(self, dataset: datasets.Dataset) -> List[float]:
This function has not been modified yet!

2024-05-28 01:55 UTC, faneshion commented on rageval/metrics/_answer_bleu.py
> +        scores = self._compute_single(predictions, references)
Wrong~~

2024-05-28 01:55 UTC, faneshion commented on rageval/metrics/_answer_bleu.py
> +        references: List[List[str]],
The same as above, using parameters `pred_answers` and `ref_answers`.

2024-05-28 01:55 UTC, faneshion commented on rageval/metrics/_answer_bleu.py
> +    def _compute_batch(self, predictions: List[str], references: List[List[str]]) -> List[float]:
The same as above, using parameters `pred_answers` and `ref_answers`.

2024-05-28 01:55 UTC, faneshion commented on rageval/metrics/_answer_chrf.py
> +        references: List[List[str]],
The same as above, using parameters `pred_answers` and `ref_answers`.

2024-05-28 01:55 UTC, faneshion commented on rageval/metrics/_answer_claim_recall.py
> +        references: List[List[str]]
The same as above, using parameters `pred_answers` and `ref_claims`.

2024-05-28 01:55 UTC, faneshion commented on rageval/metrics/_answer_claim_recall.py
> +        answer: str,
The same as above, using parameters `pred_answer` and `ref_claims`.

2024-05-28 01:55 UTC, faneshion commented on rageval/metrics/_answer_disambig_f1.py
> +        answer: str,
The same as above, using parameters `pred_answer` and `ref_answers`.

2024-05-28 01:55 UTC, faneshion commented on rageval/metrics/_answer_disambig_f1.py
> +        references: List[List[str]]
The same as above, using parameters `pred_answers` and `ref_answers`.

2024-05-28 01:55 UTC, faneshion commented on rageval/metrics/_answer_edit_distance.py
> +        answer: str,
The same as above, using parameters `pred_answer` and `ref_answer`.

2024-05-28 01:55 UTC, faneshion commented on rageval/metrics/_answer_edit_distance.py
> +        predictions: List[str],
The same as above, using parameters `pred_answers` and `ref_answers`.

2024-05-28 01:55 UTC, faneshion commented on rageval/metrics/_answer_exact_match.py
> +    def _compute_one(self, output: str, short_answers: List[List[str]]) -> float:
The same as above, using parameters `pred_answer` and `ref_answers`.

2024-05-28 01:55 UTC, faneshion commented on rageval/metrics/_answer_exact_match.py
> +        predictions: List[str],
The same as above, using parameters `pred_answers` and `ref_answers`.

2024-05-28 01:55 UTC, faneshion commented on rageval/metrics/_answer_f1.py
> +        answer: str,
The same as above, using parameters `pred_answer` and `ref_answers`.

2024-05-28 01:55 UTC, faneshion commented on rageval/metrics/_answer_f1.py
> +        predictions: List[str],
The same as above, using parameters `pred_answers` and `ref_answers`.

2024-05-28 01:55 UTC, faneshion commented on rageval/metrics/_answer_lcs_ratio.py
> +        answer: str,
The same as above, using parameters `pred_answer` and `ref_answer`.

2024-05-28 01:55 UTC, faneshion commented on rageval/metrics/_answer_lcs_ratio.py
> +        predictions: List[str],
The same as above, using parameters `pred_answers` and `ref_answers`.

2024-05-28 01:55 UTC, faneshion commented on rageval/metrics/_answer_rouge_correctness.py
>      def _compute_one(self, answer: str, gt_answers: List[str]) -> float:
The same as above, using parameters `pred_answer` and `ref_answer`.

2024-05-28 01:55 UTC, faneshion commented on rageval/metrics/_answer_rouge_correctness.py
> +    def _compute_batch(self, predictions, references) -> List[float]:
The same as above, using parameters `pred_answers` and `ref_answers`.

2024-05-28 05:23 UTC, QianHaosheng commented
I'm wondering why the load diff function isn't working.

2024-06-04 13:44 UTC, QianHaosheng commented
Now the input interface of most metrics has been updated, but some new problems have also emerged.

For example:

1. The current test is not comprehensive and needs to be completed, and the correctness of the implementation of each metrics needs to be reconfirmed.
2. The `task` part is not clearly positioned in the project. Now `test_evaluation` cannot work properly due to the interface has been changed, so it is skipped temporarily.
3. The `banchmarks` that calls metrics cannot run normally now, and need to be updated and adapted as soon as possible.
4. No metric actually performs batch calculations currently. We should consider whether to retain the batch to increase parallel calculations or temporarily abandon it.

In addition, there are some formatting issues in the project, which should be fixed in subsequent updates.

2024-06-14 01:47 UTC, faneshion approved these changes

2024-06-25 08:56 UTC, merged