Add hotpot qa
gomate-community/rageval pull request #105
Opened 2024-06-22 13:14 UTC by LittleSunshineQi

add fullwiki setting and evaluation results

2024-06-22 15:14 UTC, bugtig6351 requested changes

2024-06-22 15:14 UTC, bugtig6351 commented on benchmarks/HOTPOTQA/generate.py
>  def process_response(response: str) -> Tuple[str, str]:
The current encoding method for `gt_sent_ids` and `supporting_answer` is too redundant. Consider using a tuple in the format `(title, sent_id)` or other methods as the new index for each `supporting_answer` to simplify it. Note that you may need to adjust the F1 score implementation, as it currently only accepts string input and automatically normalizes the text.

2024-06-24 02:27 UTC, bugtig6351 approved these changes

2024-06-28 05:13 UTC, QianHaosheng approved these changes

2024-06-28 05:13 UTC, merged