upgrade python to 3.10
gomate-community/rageval pull request #122
Opened 2024-09-30 11:36 UTC by Wenshansilvia

2024-10-02 12:01 UTC, bugtig6351 requested changes

2024-10-02 12:01 UTC, bugtig6351 commented on rageval/utils/check_utils.py
> +        model = OpenAILLM("gpt-3.5-turbo-16k", "OPENAI_API_KEY")  # pragma: no cover
"gpt-3.5-turbo-16k" has been deprecated few months ago, we can use "gpt-3.5-turbo" instead.

2024-10-06 16:33 UTC, faneshion approved these changes

2024-10-10 02:04 UTC, bugtig6351 approved these changes

2024-10-10 02:04 UTC, merged