add asqa benchmark
gomate-community/rageval pull request #87
Opened 2024-03-20 14:05 UTC by bugtig6351

https://github.com/gomate-community/rageval/issues/63#issuecomment-2003796017

2024-03-20 15:15 UTC, faneshion requested changes

2024-03-20 15:15 UTC, faneshion commented on benchmarks/ASQA/evaluate.py
Maybe we should implement the benchmark with Class, as with ELI5.

2024-03-21 04:06 UTC, bugtig6351 commented on benchmarks/ASQA/evaluate.py
I think that a benchmark should focus solely on the evaluation, while the generation method should be implemented elsewhere. So I have designed an abstract class as follows: 

```python
class BaseBenchmark(ABC):

    name: str
    metrics: List[str]

    def __init__() -> None:
        ...

    @abstractmethod
    def load_dataset() -> Dataset:
        ...

    @abstractmethod
    def evaluate() -> Dataset:
        ...
    
    @abstractmethod
    def save_result() -> None:
        ...

    def get_metric(name: str) -> Callable:
        module = importlib.import_module(f"rageval.metrics")
        return getattr(module, name)
```

`load_dataset()` is used to  receive the data path, check the dataset format and load it. `evaluate()` is used to test the metric performance and attach the results to the dataset, and `save_result()` saves the result files. And we could consider adding a function in the `utils.py` to display the evaluation results by inputing a dataset with socres and outputing a result table.

And there is a problem that different metrics may require different ground truths. For instance, in ASQA benchmark, the `em` metric compares `short_answers` and `answers`, while `rouge` uses `long_answers` as ground truths. How do we deal with it? Now I am resolving this by just rebuilding dataset[`gt_answers` ] in `evaluate` function when calculating different metrics, but there is only one `gt_answers` can be saved in single result file.

2024-03-22 06:40 UTC, faneshion requested changes

2024-03-22 06:40 UTC, faneshion commented on benchmarks/ASQA/generate.py
> +def generete_answers(engine: InstructGPT, dataset: Dataset) -> Dataset:
`generate_answers`

2024-03-22 06:40 UTC, faneshion commented on benchmarks/ASQA/generate.py
> +    dataset = generete_answers(engine, dataset)
`generate_answers`

2024-03-22 06:40 UTC, faneshion commented on benchmarks/ASQA/README.md
> +
add performances in this file:

### Performances:
|  methods   | metric-1  | metric-2 |
|  ----  | ----  | ----  |
| XXXX  | 单元格 |单元格 |
| XXXX  | 单元格 |单元格 |

2024-03-25 14:09 UTC, Wenshansilvia requested changes

2024-03-25 14:09 UTC, Wenshansilvia commented on benchmarks/ASQA/README.md
> +
1. Upload dataset.json file to HuggingFace and provide a link here. 
2. Maybe its better to seperate dataset generation step and evaluate step.

2024-03-25 14:09 UTC, Wenshansilvia commented on benchmarks/ASQA/output/dataset.jsonl
Large files should be upload to Huggingface. And functions that take these files as input should be able to read from local file path as well as huggingface dataset name(load_dataset("name")).

2024-03-27 02:09 UTC, faneshion approved these changes

2024-03-27 13:04 UTC, Wenshansilvia approved these changes

2024-03-27 13:05 UTC, merged