add hotpotqa benchmark
gomate-community/rageval pull request #96
Opened 2024-04-15 08:18 UTC by LittleSunshineQi

2024-04-16 09:26 UTC, bugtig6351 requested changes

2024-04-16 09:26 UTC, bugtig6351 commented on benchmarks/HOTPOTQA/hotpotqa_benchmark.py
> +        We use the `answer` as the `gt_answers` to evaluate the string Exact Match correctness and the `gt_supporting_facts` to evaluate the F1.
Too many blank lines.

2024-04-16 09:26 UTC, bugtig6351 commented on benchmarks/HOTPOTQA/hotpotqa_benchmark.py
> +            "answer_f1": ("supporting_answer", "gt_supporting_facts"),
The usage of the F1 metric is incorrect. Please take another look at the code of `AnswerF1Correctness()`. 

When calculating the F1, the two input strings are split into word-level tokens for computation. In this benchmark, “gt_supporting_facts” is a list of supporting sentences, while “supporting_answer” is a string concatenated from the supporting sentences found by the model. Directly inputting “supporting_answer” and “gt_supporting_facts” into `AnswerF1Correctness()` will first calculate the F1 between the token set of the former and the token set of each sentence in the latter, and then take the maximum value from all the F1 scores.
The correct way is calculating the F1 score at sentence level, comparing sentences and their `sent_id` to  determine whether the model has found the appropriate sentences.

2024-04-16 11:37 UTC, Wenshansilvia requested changes
Please add readme.md file according to https://github.com/gomate-community/rageval/tree/main/benchmarks/ASQA

2024-04-16 12:07 UTC, QianHaosheng requested changes

2024-04-16 12:07 UTC, QianHaosheng commented on benchmarks/HOTPOTQA/hotpotqa_benchmark.py
> +        print(data_file)
This line may be redundant code.

2024-04-16 12:07 UTC, QianHaosheng commented on benchmarks/HOTPOTQA/run.sh
> +# 检查返回状态码
Annotations should be kept in English.

2024-04-24 08:23 UTC, bugtig6351 commented on benchmarks/HOTPOTQA/README.md
> +2. [F1](../../rageval/metrics/_answer_f1.py): utilize the model's predictions to extract supporting facts, which are identified by the model. Subsequently, we compute the F1 score by comparing these
"。"

2024-04-24 08:23 UTC, bugtig6351 commented on benchmarks/HOTPOTQA/README.md
> +1. Prepare RAG responses. By default, `hotpotqa_benchmark.py` will download the results of the `gpt_3.5_turbo` model from [our huggingface dataset](https://huggingface.co/datasets/golaxy/rag-bench) a
please update the result file on `rag-bench`, adding the scores of each metric.

2024-04-24 08:23 UTC, bugtig6351 commented on benchmarks/HOTPOTQA/hotpotqa_benchmark.py
> +        For the HotPotQA dataset, the `short_answer` and `supporting_answer` which we need to extract
For the HotPotQA dataset, we need to extract the `short_answer` and `supporting_answer`.

2024-04-25 02:21 UTC, bugtig6351 approved these changes

2024-04-25 15:33 UTC, QianHaosheng approved these changes
Good job ~

2024-04-26 03:05 UTC, Wenshansilvia approved these changes

2024-04-26 03:06 UTC, merged